import {
  Activity,
  ArrowRight,
  Ban,
  BrainCircuit,
  ChartColumn,
  ChevronDown,
  CircleCheck,
  ClipboardList,
  Clock,
  CreditCard,
  Cross,
  Download,
  Droplet,
  Factory,
  HeartPulse,
  Hospital,
  House,
  IdCard,
  Layers,
  LayoutGrid,
  Lock,
  Menu,
  Mic,
  Moon,
  Package,
  Pause,
  Pencil,
  Phone,
  Pill,
  Plus,
  Receipt,
  Search,
  ShieldCheck,
  Siren,
  SendHorizontal,
  SlidersHorizontal,
  Sparkles,
  Snowflake,
  Stethoscope,
  Sun,
  TriangleAlert,
  UserCheck,
  Users,
  Wallet,
  X,
  type LucideIcon,
} from 'lucide-react';

/**
 * The console's icon names, drawn with lucide (DESIGN_SYSTEM.md §12.1), the
 * same set as the SHRI HEALTH portal. Screens keep using these short names.
 */
const ICONS = {
  userCheck: UserCheck,
  shieldCheck: ShieldCheck,
  heartPulse: HeartPulse,
  brainPulse: BrainCircuit,
  siren: Siren,
  clock: Clock,
  checkCircle: CircleCheck,
  activity: Activity,
  lock: Lock,
  stethoscope: Stethoscope,
  sun: Sun,
  moon: Moon,
  hospital: Hospital,
  close: X,
  menu: Menu,
  pill: Pill,
  chevron: ChevronDown,
  alert: TriangleAlert,
  plus: Plus,
  package: Package,
  search: Search,
  home: House,
  droplet: Droplet,
  cross: Cross,
  receipt: Receipt,
  snow: Snowflake,
  ban: Ban,
  layers: Layers,
  clipboard: ClipboardList,
  pause: Pause,
  grid: LayoutGrid,
  edit: Pencil,
  download: Download,
  phone: Phone,
  card: CreditCard,
  wallet: Wallet,
  arrow: ArrowRight,
  chart: ChartColumn,
  users: Users,
  factory: Factory,
  badge: IdCard,
  sparkles: Sparkles,
  send: SendHorizontal,
  mic: Mic,
  sliders: SlidersHorizontal,
} satisfies Record<string, LucideIcon>;

/** A decorative line icon; the accessible name comes from the text or control beside it. */
export function Icon({
  name,
  size = 18,
  strokeWidth = 2,
}: {
  name: keyof typeof ICONS;
  size?: number;
  strokeWidth?: number;
}) {
  const Glyph = ICONS[name];
  return <Glyph size={size} strokeWidth={strokeWidth} aria-hidden="true" focusable="false" />;
}
